<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>bobs-verify</AssemblyName>
    <RootNamespace>BobsVerify</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../app/Bookstore.Data/Bookstore.Data.csproj" />
    <ProjectReference Include="../app/Bookstore.Domain/Bookstore.Domain.csproj" />
  </ItemGroup>
</Project>
